using System.Net.Http.Headers;

var fullInput =
@"FFFFVVVVCCCUUUUUUUUUUUUUUTUFFFFEEEEEEEXXBBBBBBBBBBBBBBEEEEEEEEEEEEECCCCCCCCCCCCCCCQQUUUZZZZZZZZZUZZZQUUUUUUIIIIIIIIDQQQQQQQQQNNNNNNNNNNNNNNN
FFFVVVVVVVVUUUUUUUUUUUUUUUUFFFFEEEEEEEXXXBBBBBBBBEEEEEEEEEEEEEEEECCCCCCCCCCCCCCCCCQQUUZZZZZZZZZZZZZZUUUUUUUIIFFFOIDDDDQQQQQQNNNNNNNNNNNNNNNN
FFFVVVVVVVVUUXUUUUUUUUUUUUUFXEEEEEEEEEXXXBBBBBBBBEEEEEEEEEEEEEEEECCCCCCCCCCCCCCCCQQQZZZZZZZZZZZZZZZZAUUUUUUOIFFFOIIDDDQQQQQQQQNNNNNNNNNNNNNN
FFFVVVVVVFFFUXUUUUUUUXUUXQXXXXXEEEEEEXXFFBBBBBBBBBBEEEEEEEEEEEEEEECCCCCCCCCCCQQCCQQQZZZZZZZZZZZZZZGZAAUUUUOOOOOOODDDDDDDDDDQQQQNNNNNNNNNNNNN
FVVVVVVVVVVFUUUUUUUXXXXXXXXXXRRXEEECEXXBBBBBBBBBBBBHEEEEEEEEEEEEECCCCCCCCCCCCCQQQQQQZZZCZZZZDDZGZZGAAAUUUUOOOOOOOOOFFDDDDDDDDQDNNNNNNNNNNNNN
FVVVVVVVVVVFUUFFUUUUXXXXXXXXXXXXEEVEEXXBBBBBBBBBBBHHHEEEEEEEEEEEECCCCCOCCCCQQQQQQQQQQZZZZZZZZZGGGZGAAAAUUUDDOOOOOOOODDDDDDDDDDDBBBNNNNNNNNNN
FFFVVVVVVVVFFUFFUUUUXXXXXXXXXXXXXEEEEXXBBBBBBBBBBBHHHHHEZZEEWWWEECECCCOOCCCCQQQQQQQQQQQZQZZZZZGGGGGAAAAUUUUOOOOOOOOODDDDDDDDDDBBBBNNNNNFFFNN
FFFFFFVVZVVFFFFFUUUUUUUXXXXXXXXXXXEXXXXXXBBBBBBBHHHHHFFJZZEWWWWWEEECCCOOCOOQQQQQQQQQQQQQQQZZZZGGGAAAAAKKKUKOOOOOOOOOODDDDDDDDBBBBBNNNFFWFFFF
CCCCFFFVVVVVFFAFUUUUUQXXXXXXXXXXXXEXXXXXXXBBBBBBBHHHHFCJJJWWEWWWWECCOOOOOOOQQQQQQQQQQQQQQQQQQZGGKAAAAKKKKKKOOOOOOOOOOOODDDDDBBBBBBBNNFFFFFFF
CCCRCCFVVFFFFFAFAUUZZQQXXXXXXXXXXXEENXXXXXXXBYYYYYYYFFCJJJJWWWWWWWWCOOOOOOOUUQQQQQQQQQQQQQQQQQQKKKKKKKKKKKKOOOOOOOOOOODDDDDDBBBBBBBNBFFFFFFF
CCCCCCFFFFFFAAAAAAZZZZXXXXXXXXEEEEEENNVVXXXNNYYYYYYYFFCCJJJWWWWWWWWOOOOOOOOUQQQQQQQQXXXQQQQQQQQPKKKKKKKKKKKOLOOOOOOOOODDDDDDDDBBBBBBBFFFFFFF
CCCCCCCFFFAAAAAAAZZZZZXXXXXXXXXEEEEVNNVVQQQNNYYYYYYYFFCCCWWWWWWWWWWJOOOOOOOOOQQQQQXXXXMQQQQQLQBPPKKKKKKKKKKKOOOOOOOODDDDDDDDDDDBBBBEBFFFFFFF
CCCCCHBBBFFFAAAAAAZZZXXXXXXXXXXEEEEVVVVVQNNNNYYYYYYYFFFCWWWWWWWWWWOOOOOOOOOOOOQQQQQXXXXQQQQEPPBPPPKKKKKKKKKOOOOOOJOOXDDDDDDDDDBBBBBBBBBFFFFF
BCBCCBBBBFFFAAAAAAAZZXZSXXXNXXEEEVEVAVVVNNNNNYYYYYYYFFFFFNNWFWWWWWPOOOOOOOOOOOZQQQZXXXXXPQLPPPBPPKKKKKKKKKKKKOOOOJJJXXDDDDDDDDGBBBBBBBBFFFFF
BBBBBBBBZZZZAAAABBBZZZZZZYNNNEEEVVVVVVVVVVYYYYYYYYYYFFFFNNWWWWWURWPOOOOOOOOAOOZQQQZXXXXXPPPPPPPPPUPKKKKKKKKKKPOJJJJJJXXDDDDDDDBBBBBBBBFFFFFF
BBBBBBBZZZZZZAABBBBZZZZZZNNNNEVVVVVVVVVVVVYYYYYYYYYYFFFFNNWNWWYUUAOOOOOOOOOOOJJJQHXXXXXXPPPPPPPPPPPPKKKKKKPPPPPDJJJXXXDDDDDDDGBBBBBBFFFFFFFF
BBBBBBBZZZZZZAAAZBBBZZBBBBNNNVVVVVVVVVVVVVYYYYYYYYYYMFNNNNNNWWUUUUOOOOOOOOOOOJJJHHXXXXXPPPPPPPPPPPPPKKKKPPPPPPPDJJJJXXXXDDDDDXXXBFFFFFFFFFFF
BBBBBBBFFFZZZZZZZBBBZBBBBBNNNNVVVVVVVVVVVVYYYYYYYYYYANNNNUUNUUUUUUOOOOOOOOOOJJJJJHXXXXXZPPPPPPPPPPPPPKJPYPPPPPPPJJXXXXXXDXDDXXXXKUUFFFFFFFFF
BBBBBBFFZFZZZZZZZBBBBBBBBNNNNNVVVVVVVVVVVVYYYYYYYYYYANNNUUUUUUUUUUOOOOOOOOOOJJJJJXXXXXXZPPPPPPPPPPPPPKJPPPPPPPPPJJXXXXXXXXXDXXXXXUUFFFFFFFFF
BBBBBFFZZZZZZZZZZBBBBBBBBNNNNNNNVVVVVVVVVYYYYYYYYYYAANNNNNUUUUUUUOOCOOOOOJJJJJJJJXXXXXXXCPPPPPPPPPPPPKJJPJPPPPPPXJXXXXXXXXXXXXXXXUUUUFFFFFFF
BBBBBFFZZZZZZZZZZBBBBBBBBNNNNNNNNVVVVPVVVYYYYYYYYYYYYYYNNNUUUUUUUCCCUUUUOJJJJJJJJJXXXXXXXPPPPPPPPPPPPJJJJJPPPPXXXXXXXXXXXXXVXXXXUUUUUUUUUFFF
BBBBFFFZZZZZZZZZBBBBBBDDDNNNNNNNNNVVVVVVVYYYYYYYYYYYYYYNNIUUUUUUCCCCUUUUOOOOOJJJJJXXXXXXXPPPPPPPPPPPPJDDDPPPPCXXXXCXXXXXXXVVVVUUUUUUUUUUUUFF
VBBBBBFFZZZZZZZZZZBFFBDDDDDNNNNNNNVVVVVVVYYYYYYYYYYYYYYANIIUUUUUUUUUUIIIOOOOOJJJJXXXJKXXQPPPPPPPPPPPJJDYDDPPPPPDDCCCXXXXXXVVVVSUUUUUUUUUUUFF
VBBBBFFFZZZZZZZZZZBFFBBBDDDDNNNNNNNNNNNVWYYYYYYYYYYYYYYANIIIIIUUUUUUUUIIOOOOOJJJJJJJJJUXQQPPPPPPPPEEDJDDDDPPDPPDNCCCXXXXXVVVVGUUUUUUUUUUUUFF
BBBBFFFFFZZZZZZZZZZFFFFBDDDDNNNNNNNNNNNNXYYYYYYYYYYYYYYANIIIIIIUUUUUUIIIOOOOOIJJJJJHJUUUPPPPPURRPAAADDDDPPPDDDDDDCCCCXXXXVVVVUUUUUUUUEUGGGFF
BBBFFFFFFZFZZZZZFZFFFFFBDDDNNNNNNNNNNNNNXXYYYYYYYYYYYYYAAIIIIIIIUUUUUIIIOOOOOIJJJJJUUUUUUUPNPUURRAAADDDDDDDDDDDDFCCCCXXXXXPPPPUUUUUUUGGGGGGG
FFFFFFFFFFFZZZZZFZFFFFDDDDDNNNTNNNNNNXXKXXYYYYYYYYYYYYYAIIIIIIIIUUIUUIIIOOOOOIIIJJJUUUUUUUUUPUURRAAAADDDDDDDDDDDCCCCCCXXXXPPPPGBBUUUUGGGGGGG
FFFFFFFFFFFFFZZZFFFFFFDDDDDNTTTNNNNCCXXXXXXXXMYYYYYYYYYCCIIIIIIIIIIIUIIIIIIIIIIIJTUUUUUUUUUUUUUAAAAAYYDDDDDDDDDDDDCCCEXXYXEPPGGBBUUUUGGGGGGG
FFFFFFFFFFFFFFZFFFFFFFFDTWTTTTTTNNNCCXXXXXXXXXYYYYYYYYYCCIIIQQIIIIIIUUUIIIIHHHHHHIBBUUUUUUUUUUAAAAAADDDDDDDDYEEEEECCCEXBEEEPPPGGGGGGGGGGGGGG
FFFFFFFFFFFFFFZFFFFFFFTLTTTTTTTTNNLXXXXXXXXXXXYYYYYYYYYIIIIIIIJIIICUUHHHHIIHHHHHHIIBUUUUUUUUUUAAAAAAAAAADDDDYEEEEEEEEEEEEEEEEPGGGGGGGGGGGGGG
FPFFFFFFVVFFFFFFFFFTTTTTTTTTTTTNNNXXXXXXXXXXXXXXSSSSCCWWWIIIIWWWWIIKIHHHHHHHHHHHHLLUUUUUUUUIIAAAAAAAAAADDDDDYEEEEEEEEEEEEEEEPPGGGGGGGGGGGGGG
PPPFFFFFVFFFFFFFFFTTTTTTTTTTTTTNNNNXXXXXXXXXXXXXUUUSCUUWWWWWWWWWWIIKKHHHHHHHHHHHHRRMMUUUYUUIIIAAAAAAAAAAAAAAYYEEEEEEGEEEEEEXGGGGGGGGGGGGGGGG
PPPFFFFFFFFFFFFFFFTTTTTTTTTTTTTTNNNXXXXXXXXXKKKKUUUUUUUUWWWWWWWWWWTTTHHHHHHHHHHHHRRRRRUUURUUUIAAAVAAAAAAAAAYYEEEEEEEGGEERRRRCCGGGGGGGGGGGGGG
PPPPPPPFVVFFFFFFFFFFYTTZTTTTTTGTNNXXXXXXXXXXKKKUUUUUUUUUUWWWWWWWHHHHHHHHHHHHHHHHHRRRRRRRRRERIIIAZVAAAAAAAAAYYEEEEEEEGGGRRRRRCEEEEGGGGGGGGGGG
PPPPPPPFVVFFFFFFFFFFTTTTTTTTTTGGGGXXXXXXXXXKUUKUUUUUUUUUUUUWWWWWHHHHHHHHHHHHHHHHHRRRRRRRRRRRRRRRRVVVAAAAAAYYEEEEEEEGGGGRRRRRCEEEEEGGGGGGGGGX
PPPPPPPFVVFFFFFFFFFFAATTTTTTTAGGGGGEXXXXXXKKKUUUUUUUUUUUUUUUWWWWHHHHHHHHHHHHHHHHHRRRRRRRRRRRRRRRRVAAAAAAAAAAJJEEEEEEGGGRRRRRRTEEEEEELLLGGGXX
PPPPPPPPPVVVFFFFFFFFATTTTTTTTTGGGGGEEXXXXXKKKUUUUUUUUUUUUUUWWWIIHHHHHHHHHHHHKKKKKRRRRRRRRRRRRRRRRAAAAAAAAAAJJEEEEEEEGGGRRRRRRTEEEEEIQLXXGGXX
PPPPPPPPPVVFFFFFFFFFFLLTTSSGGGGGGGGGEXXXKKKKKKKUUUUUUUUUUUUWWWIIHHHHHHHHHHHHKKKKKKKRRRRRRRRRRRRRRABAAAAAAAJJJEEEEERRGGGRRRRRRRRQQQQQQLXXXXXX
PPPPPPPPPPPFFOFFFJJFLLLTTGGGGGGGGGGEEEEEEEKEEEEUUUUUUUUUUUUWWWIIHHHHHHHHHHHHKLLLKKKKMMMRRRRRRRRRRRRTAAAAGAJGJGGERRRRGRRRRRRRRQQQQQQQQLLXXXXX
PPSPPPPWAPPOOOFJJJLLLLLGGGGGGGGGGGGGEEEEEEEEEEEEUUUUUUUUUUUWWWWIHHHHHHHHHSSKSLLLLKKMMMMMRRRRRRRRFRTTTAAAGGGGGGGERRRRRRRRRRRRRRRQQQQQQQXXXXXX
PPSSSPPWWPOOOOOOOOOLLLLLLLGGGGGGGGGEEEEEEEEEEEEEUUUUUUUOUUUWQWUIHHHHHHHHHSSSSLLLKKKMMMMMMRRMMRRRRRTTTTTTTGGGGGGGGRRRRRRRRRRRRQQQQQQQQQXXXXXX
SSSWWWWWVPOOOOOOOOOLLLLLLLGEEEGGGGGEEEEEEEEEEEEEEUUUUUUOJJJJUUUUHHHHHHHHHSSSSSLLLLLMMMMMMMMMMMRJTTTJJTTTTTTGGGGGGGRRRRRRRRRRRQQQQQQQQWXXXXXX
SWWWWWWWWCOOOOOOOOOLLLLLLLLEEGGGGGEEEEEEEEEEEEEEEUUUUUOOOJJJUUUUHHHHHHHHHHHHSSLLLLLMMMMMMMMMHHJJJJJJJJJJTTGGGGGGGGRRRYRRRRRRRQQQQQQQQXXXXXXX
SSWWWWWWWWOOOOOOOOOLLLLLLLLELEGGGGEEEEELEEEEHEEHSSOUOUOOOOJJJUUUUSSHHHHHHHHHSSSSSSGGGMMMMMHHHCCJJJJJJJJTTTGGGGGGGGRRYYYRRQQQQQQQQQQQQQSSSXXX
OWWOOWWWOOOOOOOOOOLLLLLLLLLLLEEEEEEELLLLEEEEHHHHHHOOOOOOOOJJUUUUUUUHHHHHHHHHSSSSSSSGMMMMHHHHHAJJJJJJJJJJTTGGGGGGGGRPYYRRRQRQRRQQQQQQQQQSSXBX
OOOOOOOOOOOOOOOOOOOLLLLLLLLLLEEEEEEELLLLEEEEHHHMMMMOOOOOOOOJJUUUUUUUHHHHHHHHSSSSSAGGHHHHHHHHHAAJJJJJJJJJJTTGGGGGYGYYYYYRRRRRRQQQQQQQQIBSBBBB
OOOOOOOOOOOOOOOOOOOLLLLLFFFLLEEEEELLLLLLHEEHHHHMMMMOOOOOOOOJJUUUUUUUHHHHHHHHSSSSAAGGGHHHHHHHHHAJJJJJJJJTTTTGGGGGYYYYYYYYRRRRRRRZZZZZBIBBBBBB
OOOOOOOOOOOOOOOOROOLLLLLLLFVFEEEELLLLLLLHHHHHHHHMMOOOOOOOOOJJPPPPSSSHHHHHHHHSSSAAAGGHHHHHHHHHAAJJJJJJJJTTTTTTGTTTTYYYYYYYRRRRRRRZZZBBBBBBBBB
OOOOOHHHHOOOOOORRRRLLLLLLFFFFEEEELLLLLLHHHHHHHHHHMMMOOOOOOJJJPPPPJSSHHHHHHHHSSAAAAAGHHHHHHHHAAAJJJJJJJTTTTTTTTTTTTYYYYYYYRRRRRRRBZZBBBBBBBBB
OOOOHHHHHOOOOORRRRRRRLLLLYFFFFLLLLLLLLLHHHHHHHHHHMMOOOOOOJJJJPJPJJSSHHHHHHHHSAAAAAAAHAHHHHHHAAAAJJJJTTTTTTTTTTTYYYYYYYYYYRRRRRRRBBBBBBBBBBBB
OOOOHHHHOOOOOOORRRRLLLLLYYFFFFFLLLLLLFFHHHHHHHHHHHOOOOOOOJJJJJJJJJJJHHHHHHHHSSAVAAAAAAAAHHHHHAAAJJJTTTTTTTTTTYYYYYYYYYYYYYRRRRRRDDFBBBBBBBBB
OOOOOOHOOOOOOORRRRRLLHLLYYFFFFFFLLLLFFFFFHHHHHHHHHJJOOOOOJJJJJJJJJJJJPPSSPPPSVAVVAAAUAUAHHHHAAAAAJJAATTAAAAATYYYYYYYYYYYYYVRRZZZDDDBUBBBBBBB
OOOOOOOOOOOOOOOORRRLLHHHHFFFFFFFFLFFFFFFFHHHHHHHHJJJJOOOJJJJJJVJJJJJJPPPPPPPVVVVVVUUUAUAAAAAAAAAAAAAATAAAAAAAOYYYYYYYYYYTYVRZZZZDDDBBBBBBBBB
OOOOOOOOKKOOOORRRRRRLHHHHFFFFFFFFFFFFFFFFHHHHHHHHJJJJJOJJJJVVVVVJOOJPPMPPPPVVVVVEUUUUUUUAAAAAAAAAAAAAAAAAAAAAUUUUYYYYYYYYYYYZZZZZZZZBBBBBBBJ
OOOOUUOOKKOOOOKRRRRBHHHHHFFFFFFFFFFFFFFFHHHHHHHHHHSSJJJJJPPPPPPQOOOJPPPPPPPYYVVVUUUUUUUUAAAAAAAAAAAAAAAAAAAAAAUUYYYYYYYYYYYZZZZZZCCZZBBBBBBJ
OOOUUUUKKKKKKKKRRRRHHHHVHHRFFFFFFFFFCFHHHHHHHHHHHHSSSJJJPPPPPPQQQOOOPPPPPPPPPOVKUUUUUUUUUUAAAAAAAAAAAAAAAAAAAUUUYYYYYYYYYYLEEEZZCCCCCCBBOBVJ
POOUUUUKKKKKKKGGRRSSHHVVVRRRFFFFFFFCCCCCHHHCHHHHHHRSSJJJPPPFPPQQVOOOOOPPPPOPOOUUUUUUUUUUUAAAAAAAAAAAAAAAAAAAAAUUYYYYYYYYYLLEEELZCCCCCCXBOVVJ
POUUUUUKKKKKKKSSRRRSHHRRRRRRRRFFFFCCCCCCCHHCHHHHHHSSSSSPPPPPPPPQVOKKKOOOOOOOOOUUUUUUUUUUAAAAAAAAAAAAAAAAAAAAAUUUYYYYYYYYYRRRRRRRRRRCCCCCOVVJ
POUUUUUUKKJJYYYSRSSSHRRRRRRRRRRCFCCICCCCCCCCHHHHEEEEEEEPPPPPPPPQVVVKKKOOOOOOOOOUUUUUUUUUAAAAAAAAAAAAAAAAAAAAAAUUUYYYYYYYYRRRRRRRRRRCCCCCCVVV
PPUUUUUUJJJJJJSSSSSBBIRRRRRRRRRCFCCCCCCCCCCCCCEEEEEEEEEPPPPPPPPQVVVKKOOOOOOOOOTPPUUUUUAAAAAAAAAAAAAAAAAAAAAAUUUUUUYYUUYYYRRRRRRRRRRCCCCCVVVD
UUUUUUJUJJJJHJSSSSSBBRRRRRRRRRRCCCCCCCCCCCCCCCEEEEEEEEEPPPPPPPPQVVHKKKOOOOOOOOTPPPUUUUAUAAAAAAAAAEAAAAANGAAAUUUUUUUYUULYLRRRRRRRRRRVVVVVVVVD
JUUUJJJJJJJJJESSSBBBBRRRRRRRRRRCPCCCCCCCCCCCCCEEEEEEEEEPPPPPPPPPPPKKKKKOOOOOOTTPPUUUUUUUUUAAAAAAAEEEAANNNNNUUUUUUUUUUULLLRRRRRRRRRRVVVVVVVVD
JJUJJJJJJJJJJSSSSVBBBRRRRRRRRRRRPCRCCCCCGCCCCCEEEEEESPPPPPPPPPPPPPKKKKKKKOOOOTTPPPUUUUUUUUAAEEEEEEEEANNNNNNUUUUUUUUUUUUULRRRRRRRRRRVVVVVVVVV
JJJJJJJJJJJJUUUBBBBBBCCCCRRRRRRRKRRRRRRRCCCCCCEEEEEESPPPPGPPPPGPKKKKKKKJKTTTTTTTTUUUUUHUUUUUUEEEEEEENNNUUUUUUUUUUUUUUULULRRRRRRRRRRVVVVVVVVV
JJJJJJJZZZJUUUUUUCBBCCCCCCCRRRUKKKKRRRRCCCCCCCEEEEEEGGGPGGPGGPGGKKKKKKKKKTTTTTTTTTUUHHHHUUUUUEEEEEEENNNNNNNUUUUUUUUURRRRRRRRRRRRRRRVVVVVVVVV
JJJJJJZZZZZUZUCCCCBBCCCCCCCCGGKKKKRRRRRCCCCCCCEEEEEEGGGGGGGGGGGGKKKKKTTTTTTTTTTTTTTUHHHHHHHHULEEEEEEGNUGGNNNNUUUUUUURRRRRRRLLLUUUUSVVVVVVVVV
JJJZJJZZZZZZZUZJCCCCCCCCCCCCCCOKKKRRRRRRCCCCCCEEEEEEGGGGGGGGGGGGGKKKKKITTTTTTTTTTTUUHHHHUUUUULEEEEEGGCGGNNNNUUZZUUUJRRRRRRRUUUUUUUUUVVVVVVVV
JJJZZZZZZZZZZZZJCCCCCCCCCCCCOOOKKKRRRRCCCCCCCCEEEEEEGGGGGGGGGGGGGGGGIIITTTTTTTTTTTTHHHUHHUUUUUEEEEEGGGGGGGGGGGGZZZUJRRRRRRRUUUUUUUUUUUUUUVVV
JZZZZZZZZZZZZZZZZCCCCCCCCCCOOKKKKKRRRCCCCCCCCCCCCPGGGGGGGGGGGGGGGGIIIZZZATTTTTTTTTHHHHUUUUUUUUAAAEEGGGGGGGGGGGGGGGLLRRRRRRRUPUUUUUUUUUUUUUVV
JZZZZZZZZZZZZZZZCCCRRCRRCCCCOORKRKRRRRCCCCCCCCCCCGGGGGGGGGGGGGGGGGGIIZZZAZTTTTTTTTTHHUUUUUUUUUUAUGGGGGGGGGGGGGGGGGGLLLLLLLLLLPPUUUUUUUUUUUVV
JZZZZZZZZZZZZZZOOCCRRRRRCCCCVORRRRRRRRRRCCCCCCCCCCGGGGGGGGGGGGGGIGIIIZZZZZTTTTTTTTTHHHUUUUUUUUUUUGGGGGGGGGGGUGGGGGGLGLLLLLLLUUUUUUUUUUUUUUVV
JJZZZZZZZZZZZZZOOOCRRRRRRCCRVVVRRRRRRRRCCLLCCCCCCGGUUUUGGGGGGGGGIGIIIZZZZTTTTTTTTTTHHHUUUUUUUUUUUGGGGGGGGGGGGMMGMMGGGLLLLLLLAUUUUUUUUUUUUUVV
JJZZZZZZZZZZZZZORRRRRRRRRRCRVVVRRRRVVRDLLLDDFCCCCUUUUUUUGGGGGGGGIIIIIZZZZTTTTTTTTTHHWWXWWWUUUUUDUDGGGGGGGGGGMFMMMMGGGGLLLLLAAAAUUUUUUUUUUVVV
JJZZZZZZZZZZZZZQQERRRRRRRRRRVVVVVVVVDDDDDDDDFFFYUUUYUUUUGGGGSSGIIIIIIIZIJTTTTTTTTTTHWWWWWWUUUUUDDDDGGGGGGGGGMMMMMMMMGGLLLLLAAAAUUUUUUUVUUUVV
JJJJZZZZZZZZZZQQRRRRRRRRRRRRRVVVVVVVVDDDDDDFFFFYYUYYYUGGGIIGSEGEEIIIIIIIJJJTTTTTTWHHWWWWWWWWWUDDDDDGGGGGGGGGPMMMMMXMMMLLLLAAAAAAUUUUUUVVVVVV
JJJJJZZZZZZZZZQQRRRRRRRRRRRRRVRRRVVVDDDDDDDDFYYYYYYYYYXXGGGGEEEEEIIIIIIJJJJJJTTTTWWWWWWWWWWWWDDGDGDGGGGYGGGGPMMMMMMMMALLAAAAAAAAUUUUVVVVVVVV
JJJJZZZZZZVQZQQRRRRRRRRRRRRRRRRRRRRDDDDDDDDDDYYYYYYYYYXXXXXEEEEEEIIEIIIJJJJJJTTTWWWWWWWWWWKKWDDGGGGGGGGVVGGGMMTMMMAMAAALAAAVAAAVXXUUUVVVVVVV
JJJJZZZZZQQQQQQRRRRRRRRRRRRRRXXRRRRRDDDDDDDDDYYYYYYYYYYXXXXXXEEEEEEEIIJJJJJJJJTTJJWWWWWWWMMMWDGGGGGGGGXVVGGGBMTMMMAAAALLAAAVVAVVXUUUVVVVVJVV
JJJJZZZULQQQQQQRRRRRRRRRRRRRRRRRRRRDDDDDDDDDDYYYYYYYYYYYXXXXXXEEEEEEJIJJJJJJJJJOXXWWWWWWWMMMDDGGGGGGGGVVVGVVMMMMMMAAAAAAAAVVVVVXXXXXVVVVJJVV
JJJUUZZULLQQQQQRRRRRRRRRRRRRRRRRRRRRRRDDDDDGYYYYYYYYYYYYXZZXXXEEEEEEJJJJJJJJJJJXXXZWWWFFFMCMDDDDGGGGGGVVVVVMMMMMMMMAAAAAAAVVVVVXXVXVVVVJJJVV
JJJUUUUUUQQQQQQRRRRRRRRRRRRRRRRRRRRRRRRDDDDDRYYYYYYYYYZYXZZXXXEEEEEEJJJJJJJJJJJXXXXFFFFFFDDMDDDDDGGGGGVVVVVAMMMMAAAAAAAVAVVVVVVVXVVVVVJJJJJV
JUUUUUUUUUQQQQQRRRRRRRRRRRRRRRRRRRRRRRRRDDDHRYYYYYYYYYZXXXZZXXEEEEEEJJJJJJJJJJJJXXXXXXXXDDDDDDDDDGGGGGGVVVVAAAMAAADAAAAVVVVVVVVYVVVVRJJJJJJV
JUUUUUUUUUQCQQQQRRRRNNRNRRRRRRRRRRRRRRRRRRRRRRYYYYYYYYZZXZCZZEEEEEEEEEJJJJJJJJJJXXXXXXDDDDDDDDDGGGGGGGGGVAAAAAAAADDDDDDVVKVVVVVYVQQJJJJJJJJJ
JJUUUUUUUUCCCCCVRRRRNNNNNRRRRRRRRRRRRRRRRRRRRRRYYYYYZZZZZZZZZZZEEEEEEEEJJJJJJJJJJXXXXXDDDDDDDDDGGGGGGGGAAAAAAAAAADDDDDDVVVVVVVYYVQQJVJJJJJJJ
JVUUUUUUUCCCCCCVVVNNNNNYYQYYRRRRRRRRRRRRRRRRRRRYYWWYYYYZZZZZZZZEEEEEEEEJJJJJJJJJJXXXDDDRRDDDDDDGGGGGGGGGAAAAAAAAADDDDPWVPPPPVVYVVJJJJJJJJJJJ
VVUUUUUUUVVCCCVVVVNNNNYYYYYYRRRRRRRRRRRRRRRRRRRYWWWYYYYZZZZZZZYEEEEEEEEEKJJJJJJYJJXRRRRRDDDDDDDGGWWWGTIIAAAAAAAAADDPPPPPPPPPPVPRJJJJJJJJJJJJ
VVUUUUUUUUVVVVVVVVVVYNYYYYYYRRRRRRRRRRRRRRRORZZYWWWYYYYYZZZZZZZLZZZEEEEEKKKJJJYYYYYYYRRDDDDDDDDWWWWGGTIAAAAAAAAADDDPPPPPPPPPPPPJJYJJJJJJJJJJ
VVVVUUUUUVVVVVVVVVVYYYYYYYYYYRRMRRRRMMMRRRROOWZZWWWYYYYYZZZZZZZZZSSEEEEEEKKGGJYYYYYYYRBBDDDDWWWWWWWWTTIITAAAALAKDDDDPPPPPPPPPPPJJJJJJJJJJJJJ
VVVVVVUUUUVVVVVVVVVDYYYYYYYYYRMMMMRRMMRRRFWWWWWWWWWWWYYZZZZZZZZSSSSSEEKEEKKGGYYYYYYYJBBJDDDDWWWWWWWWTTTTTAAAALADDDDDPPPPPPPPPPPPPJJJJJJJJJJJ
VVVVUUUUUVVVVVVVVVVVYYYYYYYYYMMMMRRMMMMRRWWWWWWWWWWWWYWGZZZZZZQSSSSSSSKKKKKGGGYYYYYYJJJJEDDDDWWWWWWWTTTTLAALLLLXXXXXXXKXPPPPPPPPPJJJJJJJJJJJ
VVVNNNUNVVVVVVVVVVBBYYYYYYYYMMMMMMMMMMHHYWWWWWWWWWWWWWWWWWZZZZZSSSSSSSKKKKKKGGYYYYYYJJJJEDDDDWWWWWWWWLLLLLLLLLLXXXXXXXXXPPPPPPPPPFJJJJJJJJJJ
VVVNNNNNVVVVDUCVVVBBYYYYYYYOOMMMMMHMMMHHHHWWWWWWWWWWWWWCCZZZZZSSSSSSSKKKKKKKKKKKKYYYJJJJEEXXDWWWWWWLLLLLLLLLLXXXXXXXXXXXXXPPPPPPPFFFFJJFFFJJ
VVVVVNNNNVVJUUUUULUUYKYYYYOOOMMMHMHMMMHHHHWWWWWWZWWWWWWCCCCZZSSSSSSSZSYKKKKKKKKYYYYJJJJJJXXXXXXWWWWLLLLLLLLLLXXXXXXXXXXXZZZZPPPPFFFFFJFFFFJJ
RRRNNNNNNJJJUUUUUUUUUOOOYYOOOOMMHHHMMMHHHHHAWWWWZZZWWWCCCCVSSSSSSSSSSSSCKKKKKKKYYJYJJJJJXXXXXHHXXWWLLLLLLLLLLXXXXXXXXXXZZZZZZZZZZFFFFFFFFFJJ
RRRNNNNNNJJJUUUUUUUUUUOOOOOOOMMMHHHHHMMHHHAAAWWZZZZZWWCCCCVVSSSSSSSSSSSCCCKKKYYYYJJJJJJJJXXXXXXXZZZZLLLLLLLLLXXXXXXXXXXZZZZZZZZZZFFFFFFFFFFF
RRNNNNNNNNNUUUUUUUUUUUOOOOOOYHMHHHHHHHMMMMOAUWWWUUUUUUUUUURVSSSSSSSSSSCCCCCQYYYYYJJJJJJJJXXXXXXXXZZLLLLLLLLLLLXXXXXXXXXZZZZZZZZFFFFFFFFFFFFF
RRNNNNNNNNUUUUUUUUXXUOOOOOOOHHHHHHHHHHHHMOOAUUUUUUUUUUUUUUVVVSSSSSSSSCCCCCQQYYYYJJJJJJJJJXXXXXXXZZZZZYHLLLLLLLLXXXXXBBBBBBZZZZFFFFFFFFFFFFFF
NNNNNNNNNUUQUUUUUUXOUOOOOOOHHHHHHHHHHHHHOOOOOOUUUUUUUUUUVVVVVVSSSSSSSCCQQQQQQQJJJJJJJJJXJXXXXXXZZYZYYYYJJJJLLLLLXXXXXBBBBBBZBBFFFFFFFFFFFFFF
NNNNNNNNNUUUUBBBUUUOOOOOOOOOHHHHHHHHHHOOOOOOOOUUUUUUUUUUVVVVVVVVVCSSCCQQQQQQQQQJJJJJJXXXXXXXXXXYYYYYYYYJJJJLLLLLLLXBBBBBBBBBBBFFFFFFFFFFFFFF
WNNNNNNNNNUBBBBBUUYOOOOOOHHHHHHHHHHHOZOOOOOOOOUUUUUUUUUUVVVVVVVCCCOSCQQQQQQQQFFVVJJJJXXXXXXXXXXYYYYYYYJJJJJJLLLLJXXXXXBBBBBBBBBFFFFFFFFFFFFF
WNNNNNNBNBBBBBBBUUOOOOOOOOHHHHHHHHHHOOOOOOOOOOUUUUUUVVVVVVVVQVVCCCSSQQQQQQQQFFFVVJJJJNNNXXXXXXXYYYYYYYYJJJRJJXLLLXXXXXBBBBBBBBFFFFQQQFFFFFFF
WWNNNNBBBBBBBBBBBBBBOPOOOOOHHHHHHHHHHOOOOOOOOOUUUUUUUVVVVVVVQQQQCCSSXQQQQQQMFFFFFJBNNNNNXXXXXXYYYYYYYXXXJJJJXXLLXXXXXXXIBBBBBBFFFFQQQFFFFFFF
TTNNWWWBBBBBBBBBBBBBBBQOOHHHHKHHHHHHHZOOOOOOOOOOUUUUUVVVVVQQQQQQQQQQQQQQQQQFFFFFBBBNONNNXXXXXYYYYYYYYNNXXXXXXXXXXXXXXXIIBIIIIBBFFFQQQFFFFFFF
TTTTTWWBBBBBBBBBBBBBBKQOOHHHHHHHHHHHZZOOOOOOOOOOUUUUUVVVVQQQQQQQQQNQQQQQQQFFFFFFBBBOONNNXXXXXXXYYYYYNNNNXNNNNNXXXXXGXXIIIIIIIBBFFFQQQFMMFFFF
TTTTTWWBBCBCBBBBBBBBBQQQHHOOHHHHHHHHZZZOZOOOOOOOUUUUVVVVVVQQQQQQQQQQQQQQFFFFFFFFFBBOOOONXAXAXXYYYYYYYYNNNNNNNNNXXXXGGGBIIIIIIIBFFFQQQMMFFFQF
TTTTTTWWWCCCBBBCCBQBQQQQQQOHTHHHHHHHZZZZZOOOOOOOUUVVVVVVVVQQQQQQQQQQQQQFFFFFFFFFBBBOOOOOAAAAYYYYYYYYYNNNNNNNNNNXXXBGBBBBIIIIIIBFQQQQQQQQFQQQ
TTTTTTTWCCCCBCCCCQQBUQQQQQOHHHHHHHHHZZZZZZZZOOOOUVVVVVVVVQQQQQQQQQQNNQQZZZFFFFFFOOOOOOOWWWWAWYYYYYYYYYNNNNNNNNXXXBBBBIIBXIIIIIIZQQQQQQQQFQPP
TTTTTTJCCCCCCCCCCQQQQQQQQQQPHHHHHZZZZZZZZZZZZOSVVVVVVVVVVQQQQQQQQQQQNQQZZZZZZFFFOOOOOWWWWWWWWYLLYYYYYKNNNNSNNNXXXXXBBBIIIIQQQQQQQQQQQQQQMQQP
TTTTTTTCCYYYYYYCQQQQQQQQQQQPZHHZZZZZZZZZZZPZZOPVVVVVVVVVVVQQQQQQQQQQQQQZZZZZZFFFOOOOOWWWWWWWIHLYYKKYKKKNNNWWNNNNXXXXBBDIZZQQQQQQQQQQQQQQQQQQ
TTTTTTTCCYYYYYYCQQQQQQQQQQKZZZZZZZZZZZZZZPPPPPPPPVVVVVVVVVQQQQQQQQQQQZZZZZZZZZFWOWOWWWWWWWWWWHHJHKKKKKKKNNWWNXXXXXXXBZDIZZQQQQQQQQQQQQQQQQQQ
TTTTTTXXYYYYYYYCCQQQQQQQKQZZZZZZZZZZZZZPPPPPPPPPVVVVVVVVVQQQQQQQQQQQZZZZZZZZZZFWWWOWWWWWWWWWWHHHHHHHHHHWWWWYNXXXXXXXXZZZZZXZZZZQQQQQQQQQQQQG
TTTTTXXXYYYYYYYCCQQQQQQQKZZZZZZZZZZZZZZPPPPPPPPPPPVVVVVVVQVQAQQQBQQQZZZZZZZZZZZWWWWWWWWWWWWWLHHHHHHHHWWWWWWWWWXWXXXXXXXZXXXXZZZQQQQQQQQQQQGG
THTTXXXXYYYYYYYCQQQQQQQQWWZDZZZZZZZZZZZZPPPPPPPPPPPVVVVVVVVVQQQQQQQZZZZZZZZZZZWWWNWWWWWWWWWHHHHHHHHHHHHWWWWWWWWWXXXXXXXXXEEXZZQQQQQQQQQQQQGG
TTXXXXXXYYYYYYYQQQQQQQZQWWDDZZZZZHZZZZPZPPPPPPPPPPPVPPVVVVVQQQQQQUUZZZZZZZZNNNNNNNWWWWWWWWWHWHHHHHHHHHHWWWWWWWWWWXXXXXXXEEEZZZQQQQQQQQQQGGGG
XXXXXXXXYYYYYYYTQQQQQQWWWWWDDZZZHHHZZZPPPPPPPPPPPPPPPCDVDVVQQQQQQQZZZZZZZNMNNNNNNWWWWWWWWWWWWWBHHHHHHHHWWWWWWWWWWXXXXEEEEEEEMMQQQQQQQQQQGGGG
XXXXXXXXXXXXXXTTTQQTQEWWWWWWWIHIHHHHZZZPMPPQPPPPPPPPPCDVDDDQQQQBQQZZZZZZNNNNNNNNNNNNWWWWWEEWWRBHHHBBHWWWWWWWWWWWWWXXEEEEEEEEEEQQQQQGGGGGGGGG
LXLLLLXXXXXXTTTTTTTTWWWWWWWWWWHHHHHHZHHQMQQQQPPPPPPPCCDDDDDOOQBBBQQZZZZZNNNNNNNNNNNNWWWWEEEEERBHBBBBBBWWWWWWWWWWWWXXXEEEEEEEEEQQQGGGGGGGGGGG
LLLLLLXXXXXXTTTTTTTUWWWWWWWWHHHHHHHHHHHQQQQQQQPPPCPCCCCDDDDDDDBBBBZZZZZNNNNNNNNNNNNWWWWWEEEEEEBBBBBBBBWWWWWWWWWWWXXXXEEEEEEEEEQQQGGGGGGGGGGG
LLLLLLXXXXTXUUTTUUUUWWWWWWWWHHHHHHHHHHHQQQQQQQPPPCCCCCCDDDDDDDDBBBZIZHZNNNNNNNNNNNWWWWWWEEEEEABBBBBBBBWWWWWWWWWWWWXEEEEEEEEEEEQQQGGGGGGGGGGG
LLLLLLXBTTTUUUUUUUUUWWWWWWWHHHHHHHHHHHHHQQQQTTPPPCCCCCDDDDDDDDABBBBZIZZNNNNNNNNNNNWWWWWWEEEEEBBBBBBBBBBWWWBWWWWWWWWNEEEEEEEEEEQQQGGGGGGGGGGG
LLLLLLLBTTTUUUUUUUUUWWWWWWWWHHHHHHHHHHHHQQQQQQPPCCCCCDDDDDDDDDDBBBBZZZZNNNNNNNNNNNWWWWWWWVEEBBBBBBBBBBBBWBBBWWWWWWWOOEEEEEEEEEELLGGGGGGGGGGG
LLLLMMBBUUUUUUUUUUUWWWWWWWWWWHHHHHHHHHHHBQQQQBBBBBCCCCDDDDDDDDDDBBBZBBBNNNNNNNNNNNNOOWWVVVBBBBBBBBBBBBBBBBGOWWWWFOOOOEEEEEEEEEEEEAAGGGGGGGGG
LLLMMMABUUUUUUUUUUUUWWWWWWKKWHHHHHHHHHHHBQQBBBBBCCCCCDDDDDDDDDDBBBBZBBBBBBBBNNNNNOOOOWWWVBBBBBBBBBBBBBBBIIOOOWWWOOOOOOVEEEEEEAEEAAAGGGGGGGGG
LLLMMMAAAUUUUUUUUUUWWWWWWWKKWXHHHHHHHHHBBBBBBBBBCCCCCCCCDDDDDDDBBBBBBBBBBQBBOOONNOOOOWWWWBBBBBBBBBBBBBBIIIOOOWWWWOOOOOOUEEEEAAAEAAAAASSGGGAA
LLMMMAAAUUUUUUUUUUUWWWWWWWKGHHHHHHCCHBBBBBBBBBBBBCCCCCDDDDDDDUDBBBBBBBBBBBBBOOOOOOOOOWUUYBYBBBBBBBBBBBBIVVVVOOOWOOOOOOOUEAAAAAAAAAAAAASSGGAA
LQQQQQAAAUUUUUUUUUUUUUWWKKKKHKKHHHCCBBBBBBBBBBBBBBCCCCDDDDDDDDBBBBBBBBBBBBOOOOOOOOXXOWUUYYYBBBBBBBBBBBAVVVVVOOOOOOOOOOOOOOXXXXAXXAAAAASSSAAA
QQQQAQQAAAUATTTUUUUUUUUUPKKKKKKKHHCKBBBBBBBBBBBBBBBBCCDDDOKKKDBBBBBBBBBBBOOOOOOOOXXXXGUUYYBBBBBBBBBBBAAAAVVVVVOOOOOOOOOOOXXXXXXXAAXAAAAAAAAA
QQQQQQAAAAAATTTTTTTTTHXXXKKKKKKKHRKKBBBBBBBBBBBBBBBCCDDDOOKKKKBBBBBBBBBBBBBOOOXXXXXUUUUUUUBBBBBBBBZBHZAAAAAVVVOOOOOOOOOXXXXXXXXXXAXAAAAAAAAA
QQQQQQAAAAATTTTTTTTTTXXKKKKKKKKKHKKKEEBBBBBBBBBBBBBBBDDDOOKKKKKBXBBBXXBBBBOOOOOXXXXXUUUUUUBBLLLBZZZPZZZAAAAVVVVOOOOOOOOOXXXXXXXXXAXXXAAAAAAA
QQQQQQQAATTTTTTTTTTTTXXXKKXXXKKKKKKKEBBBBBBBBBBBBBBDDNDSDOOOOKKXXXXXXXXVBBOVVVVVVXXXXUUUUUBLLLLZZZZZZZZAAAAAVCVPOOOOOOOXXXXXXXXXXXXXXAAAAAAA
QQQQQQQAAATTTTTTTTXLXXXXXKXXXKKKKKEEEFFBBBBBBBBBBBBDDDDDDOOODKKXXXXXXXXVVVVVVVVVVXXXUUUUUUUZLZZZZZZZZZZZZZAAVPPPPOOOOOGGGXXXXXXXXXXAAAAAWAAA
QQQQQQQAATTTTTTTTXXXXXXXXXXXXKKKKKEEEEEEBBBDBBBBBDDDDDDDDDDDDKKXXXXXXXXVVVVVVVVVVVVXXUUUUUUZZZZZZZZZZZZZZZAAPPPPPOOOOEGGGXXXXXXXXXXXAAAAAAAA
QQQQQQQQQTTTTTTXXXXXXXXXXXXXXXKKEEEEEEEEBBBDDBBMMDDDDDDDDDDDDDKKXXXXXXXVVVVVVVVVVVVXXURUUUUZZZZZZZZZZZZZZZZZPPPPOOOOEEGGGGXXXXXXXXXXAAAAAAAA
QQQQQQQQQQMTTTTXXXXXXXXXXXXXXKKEEEEEEEEEEBBBBBMMMDDDDDDDDDDDDDXXGXXXXXXXVVVVVVVVVVVXXUUUUUUUXXZZZZZZZZZZZZPPPPPPPOOOEEGGGGGXXXXXAHXKAAAAAAAA
QQQQQQQQQQTTTTTXXXXXXXXXXXXXXXXEEEEEEEEEEEBEEBMDMDDDDDDDDDDDDIXXXXXXXZZZVVVVVVVVVVVXXUHUUUUUXXZZZZZZZZZZIZPPPPPPYYOYEEEGGGGGGGXXAHXXAAAAAAAA
QQQQQQQQQQQITTTXXXXXXXXXXXXXEEXEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDIIXXXXXXXXXVVVVVVVVVVXXXUUUUUUUUXXZZZZZZZZZZZPPPPPPYYOYEEEEGGGGGAAAAAANAAAAAAAA
QQQQQQQQQIIITTTTXXXXXXXXXXXEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDXXXXXXXXXVVVVVVVVVXXXXXXXUXUXXXZZZZZZZZZZZZPPPPPYYYYEEEGGGGGGAAAAAAAAAAAAAAA
QQQQQQQQQIIIIIIIXXXXXXXXXXXXXEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDXXXXXXXXXXVVXVXVVXXVXXXXXXXXXXXXXZZZZZZZZZZZZPPPPPPPYEEEGGGGGGGGGAAAAAAAAAAAAA
QQQQQQQQIIIIIIIXXXXXXXXXXXXXXXEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDXXXXXXXXXXXXXXXXVXXXVVXXXXXXXXXXXXXZZZZZZZZZZAAPPAAAAEEEEEGGGGGGGGAAAAAAAAAAAAA
QQQQQQQQIIIIIIIXXHXAXXXXXXRXXEEEEEEEEEEEEEEEEEEDCDWDEEDDDDDDDDXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXZZZZZZZPZAAAAAAAAAAEEEGGGGGGGAAAAAAAAAAAAAAN";

var smallInput =
@"RRRRIICCFF
RRRRIICCCF
VVRRRCCFFF
VVRCCCJFFF
VVVVCJJCFE
VVIVCCJJEE
VVIIICJJEE
MIIIIIJJEE
MIIISIJEEE
MMMISSJEEE";

var smallest =
@"OOOOO
OXOWO
OOOOO
OZOYO
OOOOO";

smallest =
@"EEEEE
EXXXX
EEEEE
EXXXX
EEEEE";

var input = smallInput;
input = fullInput;
//input = smallest;
var timer = System.Diagnostics.Stopwatch.StartNew();

var result = 0l;

var directions = new[] { new[] { 0, 1 }, new[] { 0, -1 }, new[] { 1, 0 }, new[] { -1, 0 } };

var grid = input.Split(Environment.NewLine).Select(x => x.ToCharArray()).ToArray();
var plotGrid = grid.Select((x, j) => x.Select((y, i) => new Plot { Letter = y, X = i, Y = j }).ToArray()).ToArray();
var height = grid.Length;
var width = grid[0].Length;


for (int y = 0; y < height; y++)
{
    for (int x = 0; x < width; x++)
    {
        var plot = plotGrid[x][y];
        foreach (var direction in directions)
        {
            var otherX = direction[0] + x;
            var otherY = direction[1] + y;
            if (otherX < 0 || otherY < 0 || otherX >= width || otherY >= height) { continue; }
            var otherPlot = plotGrid[otherX][otherY];
            plot.Neighbours.Add(otherPlot);
        }
    }
}

var fenceDirections = new Dictionary<char, int[]> { { 'N', new[] { 0, 1 } }, { 'S', new[] { 0, -1 } }, { 'E', new[] { 1, 0 } }, { 'W', new[] { -1, 0 } } };


var allPlots = plotGrid.SelectMany(x => x);
var regions = new Dictionary<Guid, List<Plot>>();
while (true)
{
    var somePlot = allPlots.FirstOrDefault(x => !x.RegionId.HasValue);
    if (somePlot == null) { break; }
    var visited = new HashSet<Plot>(new[] { somePlot });
    //var ignored = somePlot.GetSimilarNeighbours(visited).ToList();
    somePlot.GetSimilarNeighbours(visited);

    var regionId = Guid.NewGuid();
    var list = visited.ToList();
    list.ForEach(x => x.RegionId = regionId);
    list.ForEach(x => x.InitializeFences(fenceDirections));
    regions[regionId] = list;
}

//var perimeters = allPlots.Select(x => x.RegionId).Distinct().ToDictionary(x => x, x => 0);
var sides = allPlots.Select(x => x.RegionId).Distinct().ToDictionary(x => x, x => 0);
var areas = allPlots.GroupBy(x => x.RegionId).ToDictionary(x => x.Key, x => x.Count());


foreach (var item in regions)
{
    //var sideList = new List<(int X, int Y, char direction)>();
    var sideCount = 0;
    var fences = item.Value.Select(x => x.Fences.Select(y => (x.X, x.Y, orientation: y))).SelectMany(x => x).ToList();
    var norths = fences.Where(x => x.orientation == 'N').GroupBy(x => x.Y).Select(x => x.OrderBy(y => y.X).ToArray());
    foreach (var line in norths)
    {
        sideCount++;
        for (var i = 1; i < line.Length; i++)
        {
            if (line[i - 1].X + 1 != line[i].X)
            {
                sideCount++;
            }
        }
    }

    var souths = fences.Where(x => x.orientation == 'S').GroupBy(x => x.Y).Select(x => x.OrderBy(y => y.X).ToArray());
    foreach (var line in souths)
    {
        sideCount++;
        for (var i = 1; i < line.Length; i++)
        {
            if (line[i - 1].X + 1 != line[i].X)
            {
                sideCount++;
            }
        }
    }

    var easts = fences.Where(x => x.orientation == 'E').GroupBy(x => x.X).Select(x => x.OrderBy(y => y.Y).ToArray());
    foreach (var line in easts)
    {
        sideCount++;
        for (var i = 1; i < line.Length; i++)
        {
            if (line[i - 1].Y + 1 != line[i].Y)
            {
                sideCount++;
            }
        }
    }

    var wests = fences.Where(x => x.orientation == 'W').GroupBy(x => x.X).Select(x => x.OrderBy(y => y.Y).ToArray());
    foreach (var line in wests)
    {
        sideCount++;
        for (var i = 1; i < line.Length; i++)
        {
            if (line[i - 1].Y + 1 != line[i].Y)
            {
                sideCount++;
            }
        }
    }

    sides[item.Key] = sideCount;
}

foreach (var regionId in allPlots.Select(x => x.RegionId).Distinct())
{
    result += sides[regionId] * areas[regionId];
}



timer.Stop();
Console.WriteLine(result);
Console.WriteLine(timer.ElapsedMilliseconds + "ms");
Console.ReadLine();

void PrintGrid<T>(T[][] grid)
{
    for (int i = 0; i < grid.Length; i++)
    {
        for (int j = 0; j < grid[i].Length; j++)
        {
            Console.Write(grid[i][j]);
        }
        Console.WriteLine();
    }
}

class Plot
{
    public int X { get; set; }
    public int Y { get; set; }
    public char Letter { get; set; }
    public Guid? RegionId { get; set; }

    public List<Plot> Neighbours { get; set; } = new List<Plot>();
    public List<char> Fences { get; set; } = new List<char>();

    public void GetSimilarNeighbours(HashSet<Plot> visited)
    {
        foreach (var item in Neighbours)
        {
            if (Letter == item.Letter && !visited.Contains(item))
            {
                visited.Add(item);
                item.GetSimilarNeighbours(visited);
            }
        }
    }

    public void InitializeFences(Dictionary<char, int[]> fenceDirections)
    {
        foreach (var fenceDirection in fenceDirections)
        {
            var shouldBeFenced = !Neighbours.Any(x => x.RegionId == RegionId && x.X == X + fenceDirection.Value[0] && x.Y == Y + fenceDirection.Value[1]);
            if (shouldBeFenced)
            {
                Fences.Add(fenceDirection.Key);
            }
        }

    }


    public void TraversePerimeter(HashSet<Plot> visited, ref int sideCount, Plot previous)
    {

    }
}
